site_name: Schematise Docs
nav:
  - Home: index.md
  - Main.py: Schematise_py-and-main_py.md       
  - model.py: model_py.md
  - combinedProcess.py: combinedprocess_py.md
  - metamodelAndRAG.py: metamodelAndRAG_py.md
  - utils.py: utils_py.md

theme: readthedocs